// Generated by Xata Codegen 0.22.3. Please do not edit.
import { buildClient, buildWorkerRunner } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type DatabaseSchema = {};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Jason-K-Frank-s-workspace-ul7brh.us-east-1.xata.sh/db/xata-worker-game",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};

export const xataWorker = buildWorkerRunner<XataClient>({
  workspace: "Jason-K-Frank-s-workspace-ul7brh",
  worker: "cg545mrtbhkmciakk1vg",
});
